---
# tasks file for pd

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ pd_log_dir }}"
  - "{{ pd_data_dir }}"
  - "{{ pd_status_dir }}"

- name: deply pd binary
  copy: src="{{ resources_dir }}/bin/pd-server" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create pd data directory
  file: path={{pd_data_dir}} state=directory mode=0755

- name: create pd configuration file
  template: src=pd.toml.j2 dest={{ deploy_dir }}/conf/pd.toml mode=0644

- name: create pd startup script
  template: src=start_pd.sh.j2 dest={{ deploy_dir }}/scripts/run_pd.sh mode=0755

- name: create pd startup script
  template: src={{ item }}.j2 dest={{ deploy_dir }}/scripts/{{ item }} mode=0755
  with_items:
  - start_{{ role_name }}.sh
  - stop_{{ role_name }}.sh

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [pd_peer_port ~ '/tcp', pd_client_port ~ '/tcp'] + firewalld_ports }}"

