---

- name: create deploy directories
  file: path="{{ deploy_dir }}/{{ item }}" state=directory mode=0755
  with_items:
  - opt

- name: deploy supervise binary
  copy: src="{{ resources_dir }}/bin/{{ item }}" dest="{{ deploy_dir }}/bin/" mode=0755
  with_items:
  - supervise
  - svc
  - svstat

- name: deploy grafana binary
  unarchive: src={{ resources_dir }}/grafana-3.1.1-1470047149.linux-x64.tar.gz dest={{ deploy_dir }}/opt/

- name: rename grafana deploy dir
  shell: creates="{{ deploy_dir }}/opt/grafana" mv {{ deploy_dir }}/opt/grafana-3.1.1-* "{{ deploy_dir }}/opt/grafana"  

