---

- name: create deploy directories part 1
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/opt"

- name: deploy grafana binary
  unarchive: >
    creates="{{ deploy_dir }}/opt/grafana/bin/grafana-server"
    src={{ downloads_dir }}/grafana.tar.gz dest={{ deploy_dir }}/opt/

- name: rename grafana deploy dir
  shell: >
    creates="{{ deploy_dir }}/opt/grafana/bin/grafana-server"
    mv {{ deploy_dir }}/opt/grafana-4.0.0-* "{{ deploy_dir }}/opt/grafana"

- name: create deploy directories part 2
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ grafana_log_dir }}"
  - "{{ grafana_status_dir }}"
  - "{{ grafana_data_dir }}"
  - "{{ grafana_dashboards_dir }}"
  - "{{ grafana_plugins_dir }}"

- name: create grafana configuration file
  template: src=grafana.ini.j2 dest={{ deploy_dir }}/opt/grafana/conf/grafana.ini mode=0644

- name: push data source file
  template: src=data_source.json.j2 dest={{ grafana_data_dir }}/data_source.json mode=0644

# FIXME: how to add datasource first
- name: import grafana dashboards
  copy: src={{ item }} dest="{{ grafana_dashboards_dir }}/{{ item }}"
  with_items:
  - pd.json
  - tidb-binlog.json
  - tidb.json
  - tikv.json

- name: create grafana startup script v2
  template: src={{ item }}.j2 dest={{ deploy_dir }}/scripts/{{ item }} mode=0755
  with_items:
  - start_{{ role_name }}.sh
  - stop_{{ role_name }}.sh
