---
# Copyright 2016 PingCAP, Inc.
# The Playbook of TiDB

# use ec2.py dynamic inventory
# adapter for AWS ec2 machines

- name: perpare inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - fail: msg="ec2 group not found, please use the right inventory"
      when: "{{ not ((groups.ec2 is defined) and groups.ec2) }}"

    - fail: msg="tidb servers not found"
      when: "{{ not ((groups.tag_Type_tidb is defined) and groups.tag_Type_tidb) }}"

    - fail: msg="pd servers not found"
      when: "{{ not ((groups.tag_Type_pd is defined) and groups.tag_Type_pd) }}"

    - fail: msg="tikv servers not found"
      when: "{{ not ((groups.tag_Type_tikv is defined) and groups.tag_Type_tikv) }}"

    - name: add tidb server group
      add_host:
        groups: tidb_servers
        hostname: "{{ item }}"
      with_items: "{{ groups.tag_Type_tidb }}"
    
    - name: add pd server group
      add_host:
        groups: pd_servers
        hostname: "{{ item }}"
      with_items: "{{ groups.tag_Type_pd }}"

    - name: add tikv server group
      add_host:
        groups: tikv_servers
        hostname: "{{ item }}"
      with_items: "{{ groups.tag_Type_tikv }}"

    - name: add monitoring server group
      add_host:
        groups: monitoring_servers
        hostname: "{{ item }}"
      with_items: "{{ groups.tag_Type_monitoring }}"

    - name: add monitored server if monitoring enables
      add_host:
        groups: monitoring_servers
        hostname: "{{ item }}"
      with_items: "{{ groups.tidb_servers + groups.pd_servers + groups.tikv_servers + groups.monitoring_servers }}"
      when: "{{ (groups.monitoring_servers is defined) and groups.monitored_servers }}"

- name: prepare inventory config stage 1
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather EC2 facts.
      ec2_remote_facts:
        region: cn-north-1
        filters:
          instance-state-name: running
          "tag:ManagedBy": ansible
          "tag:Creator": andelf
      register: aws_ec2_facts

    - name: set up deploy servers
      add_host:
        groups: "{{ item.tags.Type | default('unused') }}_servers"
        hostname: "{{ item.public_ip_address }}"
      when: item.tags.Type is defined and item.tags.ManagedBy == 'ansible'
      with_items: "{{ aws_ec2_facts.instances | selectattr('state', 'equalto', 'running') | list }}"

    - name: set up monitoring server
      add_host:
        groups: monitoring_servers
        hostname: "{{ groups.tidb_servers[0] }}"
      when: groups.monitoring_servers is defined and groups.monitoring_servers

    - name: set up monitored servers
      add_host:
        groups: monitored_servers
        hostname: "{{ item.public_ip_address }}"
      when: item.tags.ManagedBy is defined and item.tags.ManagedBy == 'ansible'
      with_items: "{{ aws_ec2_facts.instances | selectattr('state', 'equalto', 'running') | list }}"

    - name: write local inventory file to aws.ini.new
      template: src=aws.inventory.ini.j2 dest={{ playbook_dir }}/aws.ini.new

- name: set fact for all generated inventory
  hosts: all
  tasks:
    - set_fact:
        ansible_user: ubuntu

- include: cluster.yml
