---
# Copyright 2016 PingCAP, Inc.
# The Playbook of TiDB

# basic kernel parameter & monitoring

- name: initializing deployment target
  hosts: all
  roles:
  - common

- name: deploying monitoring agent
  hosts: monitored_servers
  roles:
  - node_exporter

- name: deploying monitoring server
  hosts: monitoring_servers
  roles:
  - pushgateway
  - prometheus
  - grafana

# deploying TiDB cluster

- name: deploying PD cluster
  hosts: pd_servers
  roles:
  - pd

- name: deploying TiKV cluster
  hosts: tikv_servers
  roles:
  - tikv

- name: deploying TiDB cluster
  hosts: tidb_servers
  roles:
  - tidb

#- name: deploying load balance server
#  hosts: lb_servers
#  roles:
#  - haproxy


# TODO:
# - pump
# - cistern
# - drainer
# - hosts: cistern_servers

#   roles:
#   - cistern

# - hosts: drainer_servers
#   roles:
#   - drainer
