---
# Copyright 2016 PingCAP, Inc.
# The Playbook of TiDB


- name: deploying monitoring agent
  hosts: monitored_servers
  roles:
  - node_exporter

- name: deploying monitoring server
  hosts: monitoring_servers
  roles:
  - pushgateway
  - prometheus
  - grafana