---
# Copyright 2016 PingCAP, Inc.

# The playbook of TiDB


- hosts: pd_servers
  tasks:
  - name: restart PD
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh; ./start_{{ item }}.sh
    with_items:
    - pd
  - name: wait PD up
    wait_for: host={{ ansible_default_ipv4.address }} port={{ pd_client_port }} delay=10 state=present

- hosts: tikv_servers
  tasks:
  - name: restart TiKV
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh; ./start_{{ item }}.sh
    with_items:
    - tikv
  - name: wait TiKV up
    wait_for: host={{ ansible_default_ipv4.address }} port={{ tikv_port }} delay=10 state=present


- hosts: tidb_servers
  tasks:
  - name: restart TiDB
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh; ./start_{{ item }}.sh
    with_items:
    - tidb

  - name: wait TiDB up
    wait_for: host={{ ansible_default_ipv4.address }} port={{ tidb_port }} delay=10 state=present
    