---
# Copyright 2016 PingCAP, Inc.

# The playbook of TiDB
- name: gather all facts
  hosts: all
  gather_facts: true
  tags:
    - always
  roles:
    - common
  vars:
    tuning_kernel_parameters: false


- name: rolling update PD cluster
  hosts: pd_servers
  gather_facts: false
  serial: 1
  tags:
    - pd
  roles:
    - pd
  tasks:
    - name: restart PD
      tags:
        - restart
      shell: cd {{ deploy_dir }}/scripts && ./stop_pd.sh; ./start_pd.sh

    - name: wait PD up
      tags:
        - restart
      wait_for: host={{ ansible_default_ipv4.address }} port={{ pd_client_port }} state=present

- name: rolling update TiKV cluster
  hosts: tikv_servers
  gather_facts: false
  serial: 1
  tags:
    - tikv
  roles:
    - tikv
  tasks:
    - name: restart TiKV
      tags:
        - restart
      shell: cd {{ deploy_dir }}/scripts && ./stop_tikv.sh; ./start_tikv.sh

    - name: wait TiKV up
      tags:
        - restart
      wait_for: host={{ ansible_default_ipv4.address }} port={{ tikv_port }} state=present

- name: rolling update TiDB cluster
  hosts: tidb_servers
  gather_facts: false
  serial: 1
  tags:
    - tidb
  roles:
    - tidb
  tasks:
    - name: restart TiDB
      tags:
        - restart
      shell: cd {{ deploy_dir }}/scripts && ./stop_tidb.sh; ./start_tidb.sh

    - name: wait TiDB up
      tags:
        - restart
      wait_for: host={{ ansible_default_ipv4.address }} port={{ tidb_port }} state=present
