---
# Copyright 2016 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

# The rolling update playbook of TiDB

- name: check config locally
  hosts: localhost
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_static

- name: gather all facts, and check dest
  hosts: all
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_dynamic


- name: rolling update PD cluster
  hosts: pd_servers
  any_errors_fatal: true
  serial: 1
  tags:
    - pd

  pre_tasks:
    - name: stop PD by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_pd.sh
      when: not use_systemd

    - name: stop PD by systemd
      systemd: name=pd.service state=stopped
      become: true
      when: use_systemd and ansible_user != "root"

    - name: stop PD by systemd
      systemd: name=pd.service state=stopped
      when: use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait PD down
      wait_for: host={{ ansible_host }} port={{ pd_client_port }} state=stopped

  roles:
    - pd

  post_tasks:
    - name: start PD by supervise
      shell: cd {{ deploy_dir }}/scripts && ./start_pd.sh
      when: not use_systemd

    - name: start PD by systemd
      systemd: name=pd.service state=started
      become: true
      when: use_systemd and ansible_user != "root"

    - name: start PD by systemd
      systemd: name=pd.service state=started
      when: use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait PD up
      wait_for: |
        host={{ ansible_host }} port={{ pd_client_port }} state=present
        send='GET /pd/api/v1/members HTTP/1.0\r\n\r\n' search_regex='200 OK'


- name: rolling update TiKV cluster
  hosts: tikv_servers
  any_errors_fatal: true
  serial: 1
  tags:
    - tikv

  pre_tasks:
    - name: stop TiKV by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_tikv.sh
      when: not use_systemd

    - name: stop TiKV by systemd
      systemd: name=tikv@{{ tikv_port }}.service state=stopped
      become: true
      when: use_systemd and ansible_user != "root"

    - name: stop TiKV by systemd
      systemd: name=tikv@{{ tikv_port }}.service state=stopped
      when: use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait TiKV down (via Port)
      wait_for: host={{ ansible_host }} port={{ tikv_port }} state=stopped

    - name: wait TiKV down (via PID)
      wait_for_pid: pid_file={{ deploy_dir }}/status/tikv.pid timeout=300 state=absent

  roles:
    - tikv

  post_tasks:
    - name: start TiKV by supervise
      shell: cd {{ deploy_dir }}/scripts && ./start_tikv.sh
      when: not use_systemd

    - name: start TiKV by systemd
      systemd: name=tikv@{{ tikv_port }}.service state=started
      become: true
      when: use_systemd and ansible_user != "root"

    - name: start TiKV by systemd
      systemd: name=tikv@{{ tikv_port }}.service state=started
      when: use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait TiKV up
      wait_for_pid: |
        pid_file={{ deploy_dir }}/status/tikv.pid timeout=300
        thread_name_regex='endpoint' state=present


- name: rolling update TiDB cluster
  hosts: tidb_servers
  any_errors_fatal: true
  serial: 1
  tags:
    - tidb

  pre_tasks:
    - name: stop TiDB by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_tidb.sh
      when: not use_systemd

    - name: stop TiDB by systemd
      systemd: name=tidb@{{ tidb_port }}.service state=stopped
      become: true
      when: use_systemd and ansible_user != "root"

    - name: stop TiDB by systemd
      systemd: name=tidb@{{ tidb_port }}.service state=stopped
      when: use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait TiDB down
      wait_for: host={{ ansible_host }} port={{ tidb_port }} state=stopped

    - name: stop pump by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
      with_items:
        - pump
      when: enable_binlog and not use_systemd

    - name: stop pump by systemd
      systemd: name=pump.service state=stopped
      become: true
      when: enable_binlog and use_systemd and ansible_user != "root"

    - name: stop pump by systemd
      systemd: name=pump.service state=stopped
      when: enable_binlog and use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait pump down
      wait_for: |
        host={{ ansible_host }} port={{ pump_port }} state=stopped
      when: enable_binlog

  roles:
    - { role: pump, when: enable_binlog }
    - { role: tidb }

  post_tasks:
    - name: start pump by supervise
      shell: cd {{ deploy_dir }}/scripts && ./start_{{ item }}.sh
      when: enable_binlog and not use_systemd
      with_items:
        - pump

    - name: start pump by systemd
      systemd: name=pump.service state=started enabled=yes
      become: true
      when: enable_binlog and use_systemd and ansible_user != 'root'

    - name: start pump by systemd
      systemd: name=pump.service state=started enabled=yes
      when: enable_binlog and use_systemd and ansible_user == 'root'
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait pump up
      wait_for: |
        host={{ ansible_host }} port={{ pump_port }} state=present
      when: enable_binlog

    - name: start TiDB by supervise
      shell: cd {{ deploy_dir }}/scripts && ./start_tidb.sh
      when: not use_systemd

    - name: start TiDB by systemd
      systemd: name=tidb@{{ tidb_port }}.service state=started
      become: true
      when: use_systemd and ansible_user != "root"

    - name: start TiDB by systemd
      systemd: name=tidb@{{ tidb_port }}.service state=started
      when: use_systemd and ansible_user == "root"
      vars:
        - ansible_become: false
        - ansible_become_user: root

    - name: wait TiDB up
      wait_for: |
        host={{ ansible_host }} port={{ tidb_port }} state=present
        search_regex='TiDB'
