---
# Copyright 2016 PingCAP, Inc.

# The rolling update playbook of TiDB

- name: gather all facts
  hosts: all
  gather_facts: true
  tags:
    - always
  roles:
    - common
  vars:
    tuning_kernel_parameters: false


- name: rolling update PD cluster
  hosts: pd_servers
  gather_facts: false
  serial: 1
  tags:
    - pd
  tasks:
    - name: stop PD
      tags:
        - stop
      shell: cd {{ deploy_dir }}/scripts && ./stop_pd.sh

    - name: wait PD down
      tags:
        - stop
      wait_for: host={{ ansible_default_ipv4.address }} port={{ pd_client_port }} state=stopped


- name: rolling update TiKV cluster
  hosts: tikv_servers
  gather_facts: false
  serial: 1
  tags:
    - tikv
  tasks:
    - name: stop TiKV
      tags:
        - stop
      shell: cd {{ deploy_dir }}/scripts && ./stop_tikv.sh;

    - name: wait TiKV down
      tags:
        - stop
      wait_for: host={{ ansible_default_ipv4.address }} port={{ tikv_port }} state=stopped


- name: rolling update TiDB cluster
  hosts: tidb_servers
  gather_facts: false
  serial: 1
  tags:
    - tidb
  tasks:
    - name: stop TiDB
      tags:
        - stop
      shell: cd {{ deploy_dir }}/scripts && ./stop_tidb.sh;

    - name: wait TiDB down
      tags:
        - stop
      wait_for: host={{ ansible_default_ipv4.address }} port={{ tidb_port }} state=stopped


- hosts: monitored_servers
  gather_facts: false
  tasks:
    - name: stop node_exporter
      shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
      with_items:
      - node_exporter

- hosts: monitoring_servers
  gather_facts: false
  tasks:
  - name: stop monitoring modules
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
    with_items:
    - pushgateway
    - prometheus
    - grafana
