---

tikv_port: 20160

tikv_data_dir: "{{ deploy_dir }}/data"

# log level: trace, debug, info, warn, error, off.
tikv_log_level: "info"
tikv_log_dir: "{{ deploy_dir }}/log"
tikv_log_filename: "tikv.log"
tikv_stderr_filename: "tikv_stderr.log"

tikv_metric_interval: "15s"

tikv_conf_dir: "{{ deploy_dir }}/conf"

labels: {}

wal_dir: ""

raftdb_path: ""

# docker settings
tikv_docker_log_dir: "{{ tikv_log_dir }}/tikv"
