---

tikv_port: 20160

tikv_data_dir: "{{ deploy_dir }}/data"

# log level: trace, debug, info, warn, error, off.
tikv_log_level: "info"
tikv_log_dir: "{{ deploy_dir }}/log"
tikv_log_filename: "tikv.log"
tikv_stderr_filename: "tikv_stderr.log"

tikv_capacity: "0"

tikv_metric_interval: "2s"

labels: {}

wal_dir: ""

raftdb_path: ""

#tikv_labels:
#  zone: cn
