---
- name: Determine if Atomic
  stat: path=/run/ostree-booted
  register: os_tree_check
  changed_when: false
  always_run: yes

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: os_tree_check.stat.exists

- name: Create the directory used to store binaries
  file: path={{ bin_dir }} state=directory

- name: Determine if has rpm
  stat: path=/usr/bin/rpm
  register: rpm_check
  changed_when: false
  always_run: yes

- name: Set the has_rpm fact
  set_fact:
    has_rpm: true
  when: rpm_check.stat.exists

- include: rpm.yml
  when: has_rpm

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: iptables_check
  changed_when: false
  failed_when: false
  always_run: yes
  when: has_rpm

- name: Determine if iptables-services installed
  command: "dpkg -l iptables"
  register: iptables_check
  changed_when: false
  failed_when: false
  always_run: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Set the has_iptables fact
  set_fact:
    has_iptables: true
  when: iptables_check.rc == 0
