---
# Common Tasks

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ deploy_dir }}/scripts"
    - "{{ deploy_dir }}/conf"
    - "{{ backup_dir }}"
    - "{{ status_dir }}"

- name: create deploy binary directory
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/bin"
  when: deployment_method != 'docker'
