---
- name: Load essential images
  command: docker load -i "{{ binaries_dir }}/{{ item }}"
  with_items:
    - "pause-amd64_{{ pause_version }}.tar"
    - "exechealthz-amd64_{{ exechealthz_version }}.tar"
    - "kubedns-amd64_{{ kubedns_version }}.tar"
    - "kube-dnsmasq-amd64_{{ kube_dnsmasq_version }}.tar"
  ignore_errors: True

- name: Load logging images
  command: docker load -i "{{ binaries_dir }}/{{ item }}"
  with_items:
    - "elasticsearch_{{ elasticsearch_version }}.tar"
    - "fluentd-elasticsearch_{{ fluentd_elasticsearch_version }}.tar"
    - "kibana_{{ kibana_version }}.tar"
  when: cluster_logging
  ignore_errors: True

- name: Load monitering images
  command: docker load -i "{{ binaries_dir }}/{{ item }}"
  with_items:
    - "prometheus_{{ prometheus_version }}.tar"
    - "grafana_{{ grafana_version }}.tar"
    - "node-exporter_{{ node_exporter_version }}.tar"
    - "pushgateway_{{ pushgateway_version }}.tar"
    - "alertmanager_{{ alertmanager_version }}.tar"
  when: cluster_monitoring
  ignore_errors: True

- name: Load dashboard images
  command: docker load -i "{{ binaries_dir }}/{{ item }}"
  with_items:
    - "kubernetes-dashboard-amd64_{{ kube_dashboard_version }}.tar"
  when: kube_ui
  ignore_errors: True

- name: Load tidb images
  command: docker load -i "{{ binaries_dir }}/{{ item }}"
  with_items:
    - "pd_{{ pd_version }}.tar"
    - "tidb_{{ tidb_version }}.tar"
    - "tikv_{{ tikv_version }}.tar"
  ignore_errors: True
