# TCP port used by etcd clients. Also resides in
# roles/etcd/defaults/main.yaml
etcd_client_port: 2379

#flannel_version
flannel_version: 0.5.5

#The backend that flannel should use
flannel_backend: vxlan

flannel_releases_dir: "/opt"

bin_dir: "/opt/bin"

flannel_config_dir: "/etc/sysconfig"
