---
- name: MONITORING | Assures {{ kube_config_dir }}/addons/cluster-monitoring dir exists
  file: path="{{ kube_addons_dir }}/cluster-monitoring" state=directory

- name: MONITORING | Install monitoring tools
  template:
    src="cluster-monitoring/{{ item }}.j2"
    dest="{{ kube_addons_dir }}/cluster-monitoring/{{ item }}"
    mode=0644
    owner=root
    group=root
  with_items:
    - node-exporter.yaml        # node-exporter DaemonSet
    - grafana-config.yaml
    - grafana-rc.yaml
    - grafana-svc.yaml
    - prometheus-config.yaml
    - prometheus-rc.yaml
    - prometheus-svc.yaml
    # grafana 4.0 support alerting, maybe we can remove alertmanager
    - alertmanager-config.yaml
    - alertmanager-rc.yaml
    - alertmanager-svc.yaml
    # when TiDB support pull, we can remove pushgateway
    - pushgateway-rc.yaml
    - pushgateway-svc.yaml
