---
- name: reload systemd
  command: systemctl --system daemon-reload
  notify:
    - restart daemons
  when: init_system == "systemd"

- name: restart daemons
  command: /bin/true
  notify:
    - restart kubelet
    - restart proxy

- name: restart kubelet
  service: name=kubelet state=restarted

- name: restart proxy
  service: name=kube-proxy state=restarted

- name: restart iptables
  service: name=iptables state=restarted

# - name: load fluentd_es image
#   command: docker load -i "{{ docker_image_dir }}/fluentd-elasticsearch_{{ fluentd_es_version }}.tar"
