---

- name: create log directory
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pump_docker_log_dir }}"

- name: deploy tidb-binlog image
  copy: src="{{ downloads_dir }}/tidb-binlog.tar" dest="{{ deploy_dir }}/images" mode=0755

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_docker.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run

- name: create startup script
  include_role:
    name: docker
  vars:
    this_role_name: pump
    service_name: pump

- name: load docker image from archive
  docker_image:
    state: present
    force: yes
    name: pingcap/tidb-binlog
    tag: "{{ tidb_version }}"
    load_path: "{{ images_dir }}/tidb-binlog.tar"
