---
# tasks file for pump

- name: create deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pump_data_dir }}"
  - "{{ pump_log_dir }}"
  - "{{ deploy_dir }}/status/{{ role_name }}"

- name: deploy pump binary
  copy: src="{{ resources_dir }}/bin/pump" dest="{{ deploy_dir }}/bin/" mode=0755

- name: deploy supervise
  include_role:
    name: supervise
  when: deployment_method == 'supervise'
  vars:
    this_role_name: pump

- name: deploy systemd
  include_role:
    name: systemd
  when: deployment_method == 'systemd'
  vars:
    this_role_name: pump
    service_name: pump

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [pump_port ~ '/tcp'] + firewalld_ports }}"
