---
# tasks file for tidb

- name: create deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pump_data_dir }}"
  - "{{ pump_log_dir }}"
  - "{{ pump_status_dir }}"

- name: deply pump binary
  copy: src="{{ resources_dir }}/bin/pump" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create pump startup script
  template: src={{ item }}.j2 dest={{ deploy_dir }}/scripts/{{ item }} mode=0755
  with_items:
  - start_{{ role_name }}.sh
  - stop_{{ role_name }}.sh

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [pump_port ~ '/tcp'] + firewalld_ports }}"
