---
# tasks file for pump

- name: create deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pump_data_dir }}"
  - "{{ pump_log_dir }}"
  - "{{ status_dir }}"

- include: "{{ deployment_method }}_deployment.yml"

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [pump_port ~ '/tcp'] + firewalld_ports }}"
