---

- name: create deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ pushgateway_log_dir }}"
  - "{{ pushgateway_status_dir }}"

- name: deply pushgateway binary
  copy: src="{{ resources_dir }}/bin/pushgateway" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create pushgateway startup script
  template: src={{ item }}.j2 dest={{ deploy_dir }}/scripts/{{ item }} mode=0755
  with_items:
  - start_{{ role_name }}.sh
  - stop_{{ role_name }}.sh
