---
- name: Enable apt through https
  apt:
    name='{{ item }}'
    state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Enable repository mirror
  copy: src="{{ mirror_site }}-ubuntu-sources.list" dest=/etc/apt/sources.list

- name: Install essential packages
  apt:
    name='{{ item }}'
    state=present
    install_recommends=no
    update_cache=yes
  with_items:
    - openssl
    - curl
    - tar
    - socat
    - python-yaml

- name: Add dockerproject key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add dockerproject repo for debian
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo debian-jessie main'
    state=present
  when: ansible_distribution == 'Debian'

- name: Add dockerproject repo for ubuntu
  apt_repository:
    repo='deb https://mirrors.tuna.tsinghua.edu.cn/docker/apt/repo ubuntu-trusty main'
    state=present
  when: ansible_distribution == 'Ubuntu'

- name: Install docker
  apt:
    name=docker-engine
    state=latest
    install_recommends=no
    update_cache=yes
