---
- name: Ensure bin_dir exists
  file:
    path="{{ bin_dir }}"
    recurse=yes
    state=directory

- name: Create system etcd group
  group:
    name=etcd
    state=present

- name: Create system etcd user
  user:
    name=etcd
    comment="Etcd user"
    shell=/sbin/nologin
    state=present
    system=yes
    groups=etcd

- name: Ensure {{ etcd_data_dir }} exists
  file:
    path="{{ etcd_data_dir }}"
    recurse=yes
    state=directory
    owner=etcd

- name: Extract tar file
  unarchive:
    src="{{ binaries_dir }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest="{{ install_path }}"
    copy=no

- name: Create symlinks
  file:
    src="{{ install_path }}/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest="{{ bin_dir }}/{{ item }}"
    state=link
    mode=0755
  with_items:
    - etcd
    - etcdctl

- name: Create upstart script
  copy: src=etcd.upstart dest=/etc/init/etcd.conf
  when: init_system == "upstart"

- name: Create systemd unit file
  copy: src=etcd.service dest=/etc/systemd/system
  notify:
    - reload systemd
  when: init_system == "systemd"
