---

- name: deploy node_exporter image
  copy: src="{{ downloads_dir }}/node-exporter.tar" dest="{{ deploy_dir }}/images" mode=0755

- name: create run script
  template:
    src: "{{ item }}_{{ role_name }}_docker.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run

- name: create startup script
  include_role:
    name: docker
  vars:
    this_role_name: node_exporter
    service_name: node_exporter

- name: load docker image from archive
  docker_image:
    state: present
    force: yes
    name: prom/node-exporter
    tag: "{{ node_exporter_tag }}"
    load_path: "{{ images_dir }}/node-exporter.tar"
