---

- include: binary_deployment.yml
  when: deployment_method != 'docker'
 
- include: supervise_deployment.yml
  when: deployment_method == 'supervise'

- include: systemd_deployment.yml
  when: deployment_method == 'systemd'

- include: docker_deployment.yml
  when: deployment_method == 'docker'

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [node_exporter_port ~ '/tcp'] + firewalld_ports }}"
