---

- name: create deploy directories
  file: creates="{{ item }}" path={{ item }} state=directory recurse=yes mode=0755
  with_items:
  - "{{ deploy_dir }}/bin"
  - "{{ deploy_dir }}/scripts"
  - "{{ deploy_dir }}/backup"
  - "{{ node_exporter_log_dir }}"
  - "{{ node_exporter_status_dir }}"

- name: deploy supervise binary
  copy: src="{{ resources_dir }}/bin/{{ item }}" dest="{{ deploy_dir }}/bin/" mode=0755
  with_items:
  - supervise
  - svc
  - svstat

- name: deply node_exporter binary
  copy: src="{{ resources_dir }}/bin/node_exporter" dest="{{ deploy_dir }}/bin" mode=0755

- name: create node_exporter startup script
  template: src=run_node_exporter.sh.j2 dest={{ deploy_dir }}/scripts/run_node_exporter.sh mode=0755

- name: create {{ role_bame }} startup script v2
  template: src={{ item }}.j2 dest={{ deploy_dir }}/scripts/{{ item }} mode=0755
  with_items:
  - start_{{ role_name }}.sh
  - stop_{{ role_name }}.sh
