---

- name: create supervise status directory
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/status/{{ role_name }}"

- name: deploy supervise
  include_role:
    name: supervise
  vars:
    this_role_name: node_exporter
