kubelet_working_dir: /var/lib/kubelet

services_enabled: true
kubelet_modified: false
proxy_modified: false

# List of Kubernetes node binaries to install.
kube_node_binaries:
  - kube-proxy
  - kubelet
