---
- name: Install Upstart Config Files
  copy:
    src="init_conf/{{ item }}.conf"
    dest="/etc/init/{{ item }}.conf"
    force=yes
    mode=0644
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Install Upstart Script Files
  copy:
    src="init_scripts/{{ item }}"
    dest="/etc/init.d/{{ item }}"
    force=yes
    mode=0755
  register: "{{ item }}_service"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Write Kubernetes Master Default files
  template: src="{{ item }}-default.j2" dest="/etc/default/{{ item }}"
  register: "{{ item }}_default"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
