---
- name: Install Upstart Config Files
  copy:
    src="init_conf/{{ item }}.conf"
    dest="/etc/init/{{ item }}.conf"
    force=yes
    mode=0644
  with_items:
    - kubelet
    - kube-proxy

- name: Install Upstart Script Files
  copy:
    src="init_scripts/{{ item }}"
    dest="/etc/init.d/{{ item }}"
    force=yes
    mode=0755
  register: "{{ item }}_service"
  with_items:
    - kubelet
    - kube-proxy

- name: Write Kubernetes Node Default files
  template: src="{{ item }}-default.j2" dest="/etc/default/{{ item }}"
  register: "{{ item }}_default"
  with_items:
    - kubelet
    - kube-proxy
