---
- name: Install Systemd unit files
  copy:
    src="{{ item }}.service"
    dest=/etc/systemd/system/{{ item }}.service
    force=yes
  register: "{{ item }}_service"
  notify:
    - reload systemd
  with_items:
    - kubelet
    - kube-proxy

- name: Install Systemd config files
  copy:
    src="environ/{{ item }}"
    dest={{ kube_config_dir }}/{{ item }}
    force=yes
  register: "{{ item }}_default"
  notify:
    - reload systemd
  with_items:
    - config
    - kubelet
    - proxy

- name: Install Systemd tmpfile
  copy:
    src="tmpfiles.d/kubernetes.conf"
    dest=/usr/lib/tmpfiles.d/kubernetes.conf
    force=yes
  notify:
    - reload systemd
