---
- name: Install system service for upstart
  include: install-upstart-files.yml
  when: init_system == "upstart"

- name: Set selinux permissive because tokens and selinux do not work together
  selinux: state=permissive policy={{ ansible_selinux.type }}
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

- name: Install system service for systemd
  include: install-systemd-files.yml
  when: init_system == "systemd"

- include: install_bins.yml
  tags:
    - binary-update

# enable cpu and memory accounting for systemd services by default
- name: Create systemd dropin directory
  file: path=/etc/systemd/system/system.conf.d state=directory mode=0755
  when: init_system == "systemd"

- name: Enable cpu and memory accounting for systemd services
  copy: src=kubernetes-accounting.conf dest="/etc/systemd/system/system.conf.d/kubernetes-accounting.conf"
  notify:
    - reload systemd
  when: init_system == "systemd"
