---
- name: Get iptables rules
  command: iptables -L --wait
  register: iptablesrules
  always_run: yes

- name: Enable iptables at boot
  service: name=iptables enabled=yes state=started
  when: ansible_distribution == "Centos" or ansible_distribution == "Redhat"

- name: Enable iptables at boot
  service: name=ufw enabled=yes state=started
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Open kubelet port with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 10250 -j ACCEPT -m comment --comment "kubelet"
  when: "'kubelet' not in iptablesrules.stdout"

# this is needed if the kube-proxy is running in userspace mode
- name: Allow redirected service traffic
  command: /sbin/iptables -I INPUT 1 -i docker0
      -j ACCEPT -m comment --comment "kube-proxy redirects"

# this is needed if the kube-proxy is running in iptables mode
- name: Allow DNATed traffic through to docker
  command: /sbin/iptables -I FORWARD 1 -o docker0
      -j ACCEPT -m comment --comment "docker subnet"

- name: Save iptables rules
  command: service iptables save
  when:  (ansible_distribution == "Centos" or ansible_distribution == "Redhat") and "'kubelet' not in iptablesrules.stdout"
