---
# Install Flannel.
- name: Install Flannel with github release
  include: install.yml

- name: Override Flannel config file directory for Debian/Ubuntu
  set_fact:
    flannel_config_dir: "/etc/flannel"
  when: init_system == 'upstart' and (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: Create config file directory
  file: path="{{ flannel_config_dir }}" state=directory

- name: Install Flannel config file
  template: src=flanneld.j2 dest="{{ flannel_config_dir }}/flanneld"
  notify:
    - restart flannel
