---
- name: Prepare and write Flannel configuration to etcd
  include: config.yml

- name: Install Flannel
  include: client.yml
  when: inventory_hostname in groups['masters'] + groups['nodes']

- include: ubuntu.yml
  when: init_system == 'upstart' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')

- include: iptables.yml
  when: has_iptables

- name: Enable flannel
  service: name=flanneld enabled=yes

- name: Start flannel
  service: name=flanneld state=started
  register: flannel_started
  notify:
    - restart docker
