---

grafana_port: 3000

grafana_status_dir: "{{ status_dir }}/grafana"

grafana_log_dir: "{{ deploy_dir }}/log"
grafana_log_filename: "grafana.log"
 
grafana_data_dir: "{{ deploy_dir }}/data.grafana"

grafana_dashboards_dir: "{{ deploy_dir }}/opt/grafana/dashboards"

grafana_plugins_dir: "{{ deploy_dir }}/opt/grafana/plugins"