---

- name: setting kernel params
  become: false
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present
  with_items:
    - { name: 'net.core.somaxconn', value: 32768 }
    - { name: 'vm.swappiness', value: 0 }
    - { name: 'net.ipv4.tcp_syncookies', value: 0 }
    - { name: 'fs.file-max', value: 1000000 }

- name: update /etc/security/limits.conf file (1/4)
  become: false
  lineinfile: >
    dest=/etc/security/limits.conf
    insertbefore='# End of file'
    line='{{ deploy_user }}        soft        nofile        1000000'
    state=present

- name: update /etc/security/limits.conf file (2/4)
  become: false
  lineinfile: >
    dest=/etc/security/limits.conf
    insertbefore='# End of file'
    line='{{ deploy_user }}        hard        nofile        1000000'
    state=present

- name: update /etc/security/limits.conf file (3/4)
  become: false
  lineinfile: >
    dest=/etc/security/limits.conf
    insertbefore='# End of file'
    line='{{ deploy_user }}        soft        core        unlimited'
    state=present

- name: update /etc/security/limits.conf file (4/4)
  become: false
  lineinfile: >
    dest=/etc/security/limits.conf
    insertbefore='# End of file'
    line='{{ deploy_user }}        soft        stack        10240'
    state=present

- name: swap - disable swap
  become: false
  shell: "[ $(swapon -s | wc -l) -ge 1 ] || (swapoff -a && return 1)"
  ignore_errors: yes
  register: swapoff_result
  changed_when: "swapoff_result.rc != 0"
