---
# Common Tasks
# - name: Turn on NTP and start on boot
#   service: name=ntpd enabled=yes state=started
#   tags:
#   - ntp

# FIXME: block + include + become not works
- block:
    - include: ./kernel_params_as_root.yml
  when:
    - ansible_user == 'root'
    - tuning_kernel_parameters


- block:
    - include: ./kernel_params_as_normal_user.yml
  when:
    - ansible_user != 'root'
    - tuning_kernel_parameters

- name: create account
  user: name={{ deploy_user }}

- name: environment check (deploy dir)
  stat: path="{{ deploy_dir }}" get_md5=false get_checksum=false
  register: deploy_dir_st

- name: environment check (supervise)
  stat: path="{{ deploy_dir }}"/bin/supervise get_md5=false get_checksum=false
  register: supervise_st
  when: deploy_dir_st.stat.isdir is defined and deploy_dir_st.stat.isdir 

- name: config skip variables
  set_fact:
    skip_create_deploy_dir: false # deploy_dir_st.stat.isuid is defined and deploy_dir_st.stat.isuid and deploy_dir_st.stat.isdir
    skip_supervise: false #supervise_st.stat.executable is defined and supervise_st.stat.executable

# - debug: msg={{ skip_create_deploy_dir }}, {{ skip_supervise }}

- name: create top deploy dir as normal user
  file: path="{{ deploy_dir }}" state=directory mode=0755 owner={{ deploy_user }}
  become: true
  when:
    - ansible_user != 'root'
    - not skip_create_deploy_dir

- name: create top deploy dir when under root
  file: path="{{ deploy_dir }}" state=directory mode=0755 owner={{ deploy_user }}
  become: false
  when:
    - ansible_user == 'root'
    - not skip_create_deploy_dir

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ deploy_dir }}/bin"
    - "{{ deploy_dir }}/scripts"
    - "{{ deploy_dir }}/conf"
    - "{{ deploy_dir }}/backup"
  when:
    - not skip_supervise

- name: all start all scripts
  template: src={{ item }}.j2 dest={{ deploy_dir }}/{{ item }} mode=0755
  with_items:
  - start_all.sh
  - stop_all.sh
