---
# Common Tasks
# - name: Turn on NTP and start on boot
#   service: name=ntpd enabled=yes state=started
#   tags:
#   - ntp

# FIXME: block + include + become not works
- block:
    - include: ./kernel_params_as_root.yml
  when:
    - ansible_user == 'root'
    - tuning_kernel_parameters


- block:
    - include: ./kernel_params_as_normal_user.yml
  when:
    - ansible_user != 'root'
    - tuning_kernel_parameters

- name: create account
  user: name={{ deploy_user }}

- name: create top deploy dir
  file: path="{{ deploy_dir }}" state=directory mode=0755 owner={{ deploy_user }}
  when:
    - ansible_user != 'root'
  become: true

- name: create top deploy dir when under root
  file: path="{{ deploy_dir }}" state=directory mode=0755 owner={{ deploy_user }}
  when:
    - ansible_user == 'root'
  become: false

- name: all start all scripts
  template: src={{ item }}.j2 dest={{ deploy_dir }}/{{ item }} mode=0755
  with_items:
  - start_all.sh
  - stop_all.sh
