---
- name: Update {{ kube_script_dir }} if this is atomic
  set_fact:
    kube_script_dir: "/usr/local/libexec/kubernetes"
  when: is_atomic and kube_script_dir == "/usr/libexec/kubernetes"

- name: Update facts if this is CoreOS or Ubuntu 14.04
  set_fact:
    bin_dir: "/opt/bin"
    kube_script_dir: "/opt/bin/kubernetes"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15
