---
# tasks file for tikv

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ tikv_log_dir }}"
  - "{{ tikv_data_dir }}"
  - "{{ tikv_status_dir }}"

- name: deply tikv binary
  copy: src="{{ resources_dir }}/bin/tikv-server" dest="{{ deploy_dir }}/bin/" mode=0755

- name: create tikv configuration file
  template: src=tikv.toml.j2 dest={{ deploy_dir }}/conf/tikv.toml mode=0644

- name: create tikv startup script
  template: src={{ item }}.j2 dest={{ deploy_dir }}/scripts/{{ item }} mode=0755
  with_items:
  - exec_{{ role_name }}.sh
  - start_{{ role_name }}.sh
  - stop_{{ role_name }}.sh

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [tikv_port ~ '/tcp'] + firewalld_ports }}"
